### ISSUE TITLE
Change LevelStore to Memory in documentation

### ISSUE THREAD

**Issue by justinmanley** [Esri/terraformer-geostore-memory#3]
On documentation website for GeoStore (http://terraformer.io/geostore/), under "Using in Node.js", the documentation still reads: `var LevelStore = require('terraformer-geostore-leveldb').LevelStore;`  There is no longer a LevelStore module...

Shouldn't that line read `var Memory = require('terraformer-geostore-memory').Memory;` ?

Holdover from a previous version?

**Comment by jgravois** [comment]
it'd definitely be good to remove the reference to `terraformer-geostore-leveldb` on the website, but the last time i tried to get the ruby environment set up locally i had nothing to show for it at the end but headaches.
